services:
  postgres:
    container_name: food_app_database
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: food_app
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: food_app_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # The command tells Redis to start using our specific config file
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      # Mount our custom config file into the container
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  backend:
    container_name: food_app_backend
    build:
      context: ./backend
      args:
        # Pass the project name variable to the Dockerfile during build
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}  
    user: root                  
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    volumes:
      -  .:/workspaces/${COMPOSE_PROJECT_NAME}:cached
      - /workspaces/${COMPOSE_PROJECT_NAME}/backend/node_modules
    working_dir: /workspaces/${COMPOSE_PROJECT_NAME}/backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: food_app
      DB_PORT: 5432
      PORT: 5000 #App port
      REDIS_URL: redis://redis:6379
      REDIS_PORT: 6379
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: food_app_frontend
    build:
      context: ./frontend
    user: root                  
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - .:/workspaces/${COMPOSE_PROJECT_NAME}:cached
      - /workspaces/${COMPOSE_PROJECT_NAME}/frontend/node_modules
    working_dir: /workspaces/${COMPOSE_PROJECT_NAME}/frontend
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:


